global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "prometheus-rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ingestion-api'
    static_configs:
      - targets: ['host.docker.internal:8001']
    metrics_path: '/metrics'

  - job_name: 'extraction-service'
    static_configs:
      # List multiple potential ports for scaled extraction services
      - targets: 
        - 'host.docker.internal:8002' # Default
        - 'host.docker.internal:8004' # First scaled instance
        - 'host.docker.internal:8005' # Second scaled instance
    metrics_path: '/metrics'

  - job_name: 'normalization-service'
    static_configs:
      - targets: ['host.docker.internal:8003']
    metrics_path: '/metrics'

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
